const constants={
    OPEN_SIDEBAR: 'OPEN_SIDEBAR',
    CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
    ADD_PRODUCT: 'ADD_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    SET_PRODUCT_COUNT: 'SET_PRODUCT_COUNT',
    SET_CART: 'SET_CART',
    CLEAR_CART: 'CLEAR_CART',
}

export default constants