const actions = {
    SET_STATE: 'crud/SET_STATE',
    GET_ALL_PRODUCTS: 'crud/GET_ALL_PRODUCTS',
    GET_BUNDLES: 'crud/GET_BUNDLES',
    GET_ITEMS: 'crud/GET_ITEMS',
    GET_CATEGORIES: 'crud/GET_CATEGORIES',
    GET_PRODUCT: 'crud/GET_PRODUCT',
    GET_LATEST_PRODUCTS: 'crud/GET_LATEST_PRODUCTS',
    GET_FEATURED_PRODUCT: 'crud/GET_FEATURED_PRODUCT',
}

export default actions