export default {
    ADD_PRODUCT: 'cart/ADD_PRODUCT',
    REMOVE_PRODUCT: 'cart/REMOVE_PRODUCT',
    SET_PRODUCT_COUNT: 'cart/SET_PRODUCT_COUNT',
    SET_STATE: 'cart/SET_STATE',
    CLEAR_CART: 'cart/CLEAR_CART',
}